# Generated by Django 2.2.19 on 2023-03-06 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230306_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('user', 'recipe'), 'verbose_name': 'избранное', 'verbose_name_plural': 'избранные'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'default_related_name': 'ingredient', 'ordering': ('name',), 'verbose_name': 'ингредиент', 'verbose_name_plural': 'ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='ingredientperrecipe',
            options={'ordering': ('recipe', 'ingredient'), 'verbose_name': 'ингридиент на блюдо', 'verbose_name_plural': 'ингридиенты на блюда'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'default_related_name': 'tag', 'ordering': ('name',), 'verbose_name': 'тэг', 'verbose_name_plural': 'тэги'},
        ),
        migrations.AlterField(
            model_name='ingredientperrecipe',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Укажите число не менее 1'), django.core.validators.MaxValueValidator(8000, message='Укажите число до 8000')], verbose_name='количество'),
        ),
    ]
