# Generated by Django 2.2.19 on 2023-03-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20230307_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('G', 'г'), ('KG', 'кг'), ('ML', 'мл'), ('TSP', 'ч. л.'), ('TBSP', 'ст. л.'), ('PC', 'шт.'), ('AD_LIB', 'по вкусу'), ('GLASS', 'стакан'), ('DROP', 'капля'), ('HANDFUL', 'горсть'), ('SLICE', 'кусок'), ('PACK', 'пакет'), ('BUNCH', 'пучок'), ('PINCH', 'щепотка'), ('CAN', 'банка'), ('PACKAGE', 'упаковка'), ('STAR', 'звездочка'), ('SEGMENT', 'долька'), ('CLOVE', 'зубчик'), ('LAYER', 'пласт'), ('CARCASS', 'тушка'), ('POD', 'стручок')], max_length=16, verbose_name='ед. измерения'),
        ),
    ]
